Repository GSG-G11/Film-node.js-II, pull requests merged in 2022-02, with the labels that each got.

#3 2 file structure
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  public/js/main.js
  src/filmsTilte.json
  src/handler/publicHandler.js
  src/router.js
  src/server.js
  test/test.test.js
Labels: Done

#6 add data in file json
  src/filmsTilte.json
Labels: Awaiting Review

#12 handling endpoints
  public/index.html
  src/handler/publicHandler.js
  src/router.js
Labels: Awaiting Review

#13 9 search endpoint
  .eslintrc.json
  public/index.html
  public/js/dataList.js
  public/js/main.js
  public/js/search.js
  public/js/xhr.js
  src/filmsTitle.json
  src/handler/dataHandler.js
  src/router.js
Labels: Awaiting Review, Done

#16 edit port word and add script
  package.json
  src/server.js
Labels: Awaiting Review, Done

#18 add test
  package-lock.json
  package.json
  test/test.test.js
Labels: Awaiting Review, Done

#21 handler error
  public/css/style.css
  public/html/error.html
  public/imgs/blur.jpg
  public/imgs/error1.png
  public/js/xhr.js
  src/handler/dataHandler.js
  src/router.js
Labels: Done

#22 added readme file
  README.md
Labels: Awaiting Review

#25 test for /title endpoint
  test/test.test.js
Labels: Awaiting Review

#26 24 refactor
  README.md
  public/css/style.css
  public/html/error.html
  public/index.html
  public/js/main.js
  public/js/search.js
  src/handler/publicHandler.js
  src/router.js
Labels: Awaiting Review

#28 fixing responsive
  README.md
  public/css/style.css
  public/js/search.js
Labels: Awaiting Review
